name: Setup AWS infrastructure

on:
  workflow_dispatch:
    inputs:
      inst_id:
        -name: Installation ID
        -default: "0"
        -required: true


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Download terraform instructions
      # Download tf package. In future add some kind of authorization
      #run: wget http://url/get_package/${{ github.repository }}/{{ github.event.inputs.name }}/"
      run: wget https://emergencycode.pl/tf.tar.gz
    - name: Unpack
      run: tar -xzf tf.tar.gz
    - name: Update credentials
      run: |
        sed -i "s/REPLACE_AWS_KEY/${{ secrets.AWS_ACCESS_KEY_ID }}/g" tf/variables.tf
        sed -i "s/REPLACE_AWS_SECRET/${{ secrets.AWS_SECRET_ACCESS_KEY }}/g" tf/variables.tf
    
    - name: Init terraform
      run: |
        cd tf
        terraform init

    - name: Deploy terraform
      run: |
        cd tf
        terraform plan
